CREATE TABLE [Persons](
[PersonID] INT NOT NULL IDENTITY
,[FirstName] NVARCHAR(50) NOT NULL
,[Salary] DECIMAL(9,2) NOT NULL
,[PassportID] INT NOT NULL
);


CREATE TABLE [Passports](
[PassportID] INT PRIMARY KEY IDENTITY(101,1)
,[PassportNumber] NVARCHAR(8) NOT NULL
);



INSERT INTO [Persons] VALUES
('Roberto', 43300.00, 102)
,('Tom', 56100.00, 103)
,('Yana', 60200.00, 101);


INSERT INTO [Passports] VALUES
('N34FG21B')
,('K65LO4R7')
,('ZE657QP2');


ALTER TABLE [Persons]
ADD CONSTRAINT PK_PersonsId PRIMARY KEY([PersonID]);


ALTER TABLE [Persons]
ADD CONSTRAINT PassportID FOREIGN KEY([PassportID]) REFERENCES [Passports]([PassportID]);