FROM alpine

WORKDIR /soll

CMD [ "DevOps" ]

ENTRYPOINT [ "echo", "Hello" ]


# RUN apk add nano                      # Demo 1

# ENTRYPOINT [ "sleep", "200" ]         # Demo 1

# ENTRYPOINT [ "sleep", "infinity" ] 